# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Feedscan < Formula
  desc "Find active RSS/Atom feeds linked from any web page."
  homepage "https://github.com/meysam81/feedscan"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meysam81/feedscan/releases/download/v0.0.1/feedscan_0.0.1_darwin_amd64.tar.gz"
      sha256 "7631874f20a39d4bec84d90cc33787b17469900acc4a4c3970722ed3810d2498"

      define_method(:install) do
        bin.install "feedscan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meysam81/feedscan/releases/download/v0.0.1/feedscan_0.0.1_darwin_arm64.tar.gz"
      sha256 "d55bd51be50a118983ca3603aaf502b1355012acec55434331a9da278b1c2e1d"

      define_method(:install) do
        bin.install "feedscan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meysam81/feedscan/releases/download/v0.0.1/feedscan_0.0.1_linux_amd64.tar.gz"
      sha256 "f7ec211ca2ec6ab1a4ef7f3a35956c1dfbdebffe46ad1ad39e81e801042a5767"
      define_method(:install) do
        bin.install "feedscan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meysam81/feedscan/releases/download/v0.0.1/feedscan_0.0.1_linux_arm64.tar.gz"
      sha256 "2c6d53d6e7c39e4b5d162616c2e09929b4418e6ea43c924625c4bb614b5ceae1"
      define_method(:install) do
        bin.install "feedscan"
      end
    end
  end

  test do
    assert_match "feedscan", shell_output("#{bin}/feedscan -version")
  end
end
