# This file was generated by GoReleaser. DO NOT EDIT.
cask "feedscan" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "e7f57371d997cd786924c9487ddca4a58f7326a98bb5caaed5c0a4c5ef773fdd"
      url "https://github.com/meysam81/feedscan/releases/download/v#{version}/feedscan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c78b1a75ba0be59b43ee76dc196d295e83147a56ba5321ca74ab36603d89dcef"
      url "https://github.com/meysam81/feedscan/releases/download/v#{version}/feedscan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "40ca6d1d6853766fb74793a09292c9a4edb39a52360cf0ac202d5952d57da1ef"
      url "https://github.com/meysam81/feedscan/releases/download/v#{version}/feedscan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3ff70da61809b3c574e75551a4c2afaaf2b358f7188b96600c1e035a01bf2d6"
      url "https://github.com/meysam81/feedscan/releases/download/v#{version}/feedscan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "feedscan"
  desc "Find active RSS/Atom feeds linked from any web page."
  homepage "https://github.com/meysam81/feedscan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "feedscan"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/feedscan"]
    end
    puts "feedscan installed successfully."
    puts ""
    puts "Quick start:"
    puts "   feedscan -url example.com"
    puts ""
    puts "Documentation:"
    puts "   https://github.com/meysam81/feedscan"
  end

  # No zap stanza required

end
