# This file was generated by GoReleaser. DO NOT EDIT.
cask "inspect-certificate" do
  name "inspect-certificate"
  desc "Get detailed information about SSL/TLS certificates from the command line."
  homepage "https://github.com/meysam81/inspect-certificate"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inspect-certificate"

  on_macos do
    on_intel do
      url "https://github.com/meysam81/inspect-certificate/releases/download/v#{version}/inspect-certificate_darwin_amd64.tar.gz"
      sha256 "622da0bffbbd8c7f80b1971f2147e7b2771de75e42f971578351301e91cbc873"
    end
    on_arm do
      url "https://github.com/meysam81/inspect-certificate/releases/download/v#{version}/inspect-certificate_darwin_arm64.tar.gz"
      sha256 "d81f23163bca3dc45cb695beb39e7203606a66ddefa8edb32caa3e97dd7e2f19"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/meysam81/inspect-certificate/releases/download/v#{version}/inspect-certificate_linux_amd64.tar.gz"
      sha256 "cd7ec75e48bf20107bc90d512d54d82a4c06b697c1f235dffde2911478ac4358"
    end
    on_arm do
      url "https://github.com/meysam81/inspect-certificate/releases/download/v#{version}/inspect-certificate_linux_arm64.tar.gz"
      sha256 "e8c7a2e905023f4e193bac285606703a3742d16e29a18c239cc16a6dab8c20dd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/inspect-certificate"]
    end
  end

  # No zap stanza required
end
