# This file was generated by GoReleaser. DO NOT EDIT.
cask "parse-dmarc" do
  name "parse-dmarc"
  desc "Single-binary, zero-dependency DMARC parser with a modern web dashboard."
  homepage "https://github.com/meysam81/parse-dmarc"
  version "1.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parse-dmarc"

  on_macos do
    on_intel do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_darwin_amd64.tar.gz"
      sha256 "a37bbae76f9d6778f13148b84152c1ca17b375adafb6beed8c24b7996d55ee1b"
    end
    on_arm do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_darwin_arm64.tar.gz"
      sha256 "5e5b0a13247638cf4bb3ca575342530b68e11809da340285ecc9f5bc0d46f412"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_linux_amd64.tar.gz"
      sha256 "2d868ac9692b70147d004ebf8e8192f764c3bf06ba974d8f669555bb0aa3bbb2"
    end
    on_arm do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_linux_arm64.tar.gz"
      sha256 "556247516bca7bc0184c8b6f5254f74486d3de24bdf453b4d5af25a9ba6988cf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/parse-dmarc"]
    end
    puts "✨ parse-dmarc installed successfully!"
    puts ""
    puts "📝 Tip: You can enable shell completion by running:"
    puts "   parse-dmarc completion bash  # for bash"
    puts "   parse-dmarc completion zsh   # for zsh"
    puts "   parse-dmarc completion fish  # for fish"
    puts ""
    puts "📚 For more information and usage instructions, visit:"
    puts "   https://github.com/meysam81/parse-dmarc"
  end

  # No zap stanza required
end
