# This file was generated by GoReleaser. DO NOT EDIT.
cask "parse-dmarc" do
  version "1.7.0"

  on_macos do
    on_arm do
      sha256 "f9cdb39190524a04a139aeb49c100bcd3b460f691b1c66e7a1308eb641ba99a9"
      url "https://github.com/dmarcguardhq/parse-dmarc/releases/download/v#{version}/parse-dmarc_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "031a5a410391cdc2133dcdbc877f8952b28a53b12b0a2143760afed4e3fb2428"
      url "https://github.com/dmarcguardhq/parse-dmarc/releases/download/v#{version}/parse-dmarc_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ecea7daa06ad63c91e2a5737a3af6368bc511a380615e14bb519a5a2e55abe79"
      url "https://github.com/dmarcguardhq/parse-dmarc/releases/download/v#{version}/parse-dmarc_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c92faf0df7e0fe7829408898116db1fe5194e9596613dd0afd35f283d0f0a93a"
      url "https://github.com/dmarcguardhq/parse-dmarc/releases/download/v#{version}/parse-dmarc_linux_amd64.tar.gz"
    end
  end

  name "parse-dmarc"
  desc "Single-binary, zero-dependency DMARC parser with a modern web dashboard."
  homepage "https://github.com/dmarcguardhq/parse-dmarc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parse-dmarc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/parse-dmarc"]
    end
    puts "✨ parse-dmarc installed successfully!"
    puts ""
    puts "📝 Tip: You can enable shell completion by running:"
    puts "   parse-dmarc completion bash  # for bash"
    puts "   parse-dmarc completion zsh   # for zsh"
    puts "   parse-dmarc completion fish  # for fish"
    puts ""
    puts "📚 For more information and usage instructions, visit:"
    puts "   https://github.com/dmarcguardhq/parse-dmarc"
  end

  # No zap stanza required
end
