# This file was generated by GoReleaser. DO NOT EDIT.
cask "parse-dmarc" do
  name "parse-dmarc"
  desc "Single-binary, zero-dependency DMARC parser with a modern web dashboard."
  homepage "https://github.com/meysam81/parse-dmarc"
  version "1.4.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parse-dmarc"

  on_macos do
    on_intel do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_darwin_amd64.tar.gz"
      sha256 "0248f7c9b2ea1c2232a283a0ed5d1d16dc1ee2e24092d58cb1ae2a0474cd9b20"
    end
    on_arm do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_darwin_arm64.tar.gz"
      sha256 "2ec83b83a760f0ef810bf994a4763255cf2e647b6b68ea506bd98537732f6f69"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_linux_amd64.tar.gz"
      sha256 "f6a0748cd4878dfefd239320fdee10e50e1e5e1a0979b88ccddd30680eb2dc07"
    end
    on_arm do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_linux_arm64.tar.gz"
      sha256 "5b715132290df6cc396b8c288e29d6ecb63aa62897526bb888236fbe14f1b9f0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/parse-dmarc"]
    end
    puts "✨ parse-dmarc installed successfully!"
    puts ""
    puts "📝 Tip: You can enable shell completion by running:"
    puts "   parse-dmarc completion bash  # for bash"
    puts "   parse-dmarc completion zsh   # for zsh"
    puts "   parse-dmarc completion fish  # for fish"
    puts ""
    puts "📚 For more information and usage instructions, visit:"
    puts "   https://github.com/meysam81/parse-dmarc"
  end

  # No zap stanza required
end
