# This file was generated by GoReleaser. DO NOT EDIT.
cask "parse-dmarc" do
  name "parse-dmarc"
  desc "Single-binary, zero-dependency DMARC parser with a modern web dashboard."
  homepage "https://github.com/meysam81/parse-dmarc"
  version "1.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parse-dmarc"

  on_macos do
    on_intel do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_darwin_amd64.tar.gz"
      sha256 "f267da33a6efe904b21b80c0de99a72b6f0882f3d8d970b1e428549051766585"
    end
    on_arm do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_darwin_arm64.tar.gz"
      sha256 "2d57a05f8e5dca56d8d4913609e1aef6779d811807a9dcd8607096b7f2b98d8b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_linux_amd64.tar.gz"
      sha256 "27918f5b3c18300ce88056d306bfba52d791819e87071c735a85bf3e3a02507d"
    end
    on_arm do
      url "https://github.com/meysam81/parse-dmarc/releases/download/v#{version}/parse-dmarc_linux_arm64.tar.gz"
      sha256 "ca650866d849dff7a9190297cf8897890f4f5e3285dec57dca988818323a7f7b"
    end
  end

  # No zap stanza required
end
